# Generated by Django 5.1.4 on 2024-12-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('Food', 'Food'), ('Infrastructure', 'Infrastructure'), ('Roommate', 'Roommate')], max_length=50)),
                ('complaint_description', models.TextField()),
                ('facing_from_date', models.DateField()),
            ],
        ),
    ]
