# Generated by Django 5.1.4 on 2024-12-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel1app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('utr_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('hostel_name', models.CharField(max_length=255)),
                ('owner_signature', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
